## Do not edit this file in-place
## Copy to $HOME and modify values there

## required
export rl_hypothesis_2_subscription_id=""
export rl_hypothesis_2_tenant_id=""

## defaults
export rl_hypothesis_2_resource_group_name="rl_hypothesis_2_rg"
export rl_hypothesis_2_ephemeral_nodes=11 
export rl_hypothesis_2_ephemeral_node_type="Standard_D2_v2"
export rl_hypothesis_2_storage_nodes=3
export rl_hypothesis_2_storage_node_type="Standard_A2M_v2"
export rl_hypothesis_2_ai_image_tag="v0.0.2"
