## Do not edit this file in-place
## Copy to $HOME and modify values there

export rl_hypothesis_2_subscription_id=""
export rl_hypothesis_2_tenant_id=""
export rl_hypothesis_2_resource_group_name=""
