apiVersion: v1
kind: Service
metadata:
  name: viewer
  labels:
    app: viewer
spec:
  ports:
  - port: 5900
    targetPort: 5900
  type: LoadBalancer 
  selector:
    app: viewer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: viewer
spec:
  selector:
    matchLabels:
      app: viewer 
  serviceName: "viewer"
  replicas: 1 
  podManagementPolicy: "Parallel"
  template:
    metadata:
      labels:
        app: viewer 
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: viewer
        image: "{{ .Values.image }}"
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MINIO_ACCESSKEY
            valueFrom:
              secretKeyRef:
                name: minio
                key: accesskey
          - name: MINIO_SECRETKEY
            valueFrom:
              secretKeyRef:
                name: minio
                key: secretkey
          - name: POSTGRES_SECRET
            valueFrom:
              secretKeyRef:
                name: postgres
                key: postgres-secret
          - name: DISPLAY 
            value: ":99"
        ports:
        - containerPort: 5900
        imagePullPolicy: Always
        command:
          - "bash" 
          - "/app/src/scripts/viewer-entrypoint.sh"
          #- "python"
          #- "-u"
          #- "/app/src/python/debug.py"
        resources:
          requests:
            cpu: "1500m"
            memory: "5Gi"
        volumeMounts:
          - name: models-data
            mountPath: /models
      volumes: 
        - name: models-data 
          emptyDir: {}
      imagePullSecrets:
        - name: acr-creds
      nodeSelector:
        agentpool: compute
      tolerations:
        - key: kubernetes.azure.com/scalesetpriority
          operator: "Exists"
