echo Attempting controller image build...
echo Copying keys...
cp /app/service-account.json /app/${RL_HYPOTHESIS_2_REPO_DIR_NAME}/docker/controller/app/service-account.json
cp /app/${RL_HYPOTHESIS_2_REPO_DIR_NAME}/config.sh /app/${RL_HYPOTHESIS_2_REPO_DIR_NAME}/docker/controller/app/config.sh 
cp ~/.boto /app/${RL_HYPOTHESIS_2_REPO_DIR_NAME}/docker/controller/app/.boto
echo Executing build...
cd /app/${RL_HYPOTHESIS_2_REPO_DIR_NAME}/docker/controller
source docker-build.sh
echo Cleaning-up...
rm /app/${RL_HYPOTHESIS_2_REPO_DIR_NAME}/docker/controller/app/service-account.json
rm /app/${RL_HYPOTHESIS_2_REPO_DIR_NAME}/docker/controller/app/.boto
